version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static:/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery_worker
      - celery_beat
    environment:
      - DB_NAME=pilot
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  db:
    image: postgres:16.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pilot
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: celery -A IssuePilot worker -Q default,send_email -P gevent -c 200 -O fair --loglevel=info
    depends_on:
      - db
      - redis
    environment:
      - DB_NAME=pilot
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: celery -A IssuePilot beat --loglevel=info
    depends_on:
      - db
      - redis
      - celery_worker 
    environment:
      - DB_NAME=pilot
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
  
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static: