version: '3.8'

services:

  db:
    image: postgres:16.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pilot
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  static: